### ISSUE TITLE
Error when using contour 

### ISSUE THREAD

**Issue by ccruizm** [BiomedicalMachineLearning/stLearn#137]
Good day!

Great tool! I am having issues when using contour on functions like `gene_plot` or `het_plot`. See images below. What do you think the issue can be? I notice this occurs when using normalized data (and also changes if I import the data directly with stLeanr or convert from adata object). 

From anndata:
<img width="596" alt="Screenshot 2021-11-11 at 09 12 17" src="https://user-images.githubusercontent.com/37718031/141261913-d06b8561-9817-4544-9c2f-12a256004730.png">

<img width="593" alt="Screenshot 2021-11-11 at 09 12 34" src="https://user-images.githubusercontent.com/37718031/141261947-8b917770-f95c-4b24-a8b1-55bc1c893f9c.png">

Importing directly with stLearn:
<img width="599" alt="Screenshot 2021-11-11 at 09 13 10" src="https://user-images.githubusercontent.com/37718031/141262037-ae4a3ab7-ae09-461a-8ebb-d1c7d183c29e.png">

<img width="600" alt="Screenshot 2021-11-11 at 09 13 21" src="https://user-images.githubusercontent.com/37718031/141262062-a28a560f-3d8b-4633-8bbe-656eef9e9da2.png">

Also, I tried to use a setp_size lower than 1 for the normalized data to get a more defined image (similar to the one using raw counts - image below) but was not possible (`TypeError: 'float' object cannot be interpreted as an integer`). Is it possible to implement this with normalized data?

<img width="614" alt="Screenshot 2021-11-11 at 09 17 04" src="https://user-images.githubusercontent.com/37718031/141262521-484d950e-add1-4b43-b1b9-c292ce9851c8.png">

**Comment by duypham2108** [comment]
Hi, I understand this problem. The reason is the `step_size` have to be integer as the requirement of `plt.contourf` and also the range of the normalized data is low.

One solution is adding a temporally scaling or normalizing function to increase the range of the gene expression value. I will try to test it asap and back to you later. 

I also will test the different between converting from scanpy and directly from stLearn. Thanks for your report
