### ISSUE TITLE
Error from 2nd step in cell-cell interaction 

### ISSUE THREAD

**Issue by DecodeGenome** [BiomedicalMachineLearning/stLearn#142]
Hi,

when I ran "st.add.labels(data, 'tutorials/label_transfer_bc.csv', sep='\t')
st.pl.cluster_plot(data,use_label="predictions")", I got error below
#######################
......
ValueError: Length of values (3813) does not match length of index (4015)
#######################
the input data is: ~/10xGenomics_V1_BC_Block_A_Section_2
Why does this occur? how to fix it?

Thanks,

Wei

**Comment by BradBalderson** [comment]
Hi Wei,

Apologies for the late reply, have been away for the last few weeks :).

The problem is due to the relative path here: 'tutorials/label_transfer_bc.csv'
This assumes you're running the code from wherever stlearn is installed. 

To fix, you can add the path to where stlearn is installed by:

 '/your_path_to_stlearn/tutorials/label_transfer_bc.csv'

**Comment by BradBalderson** [comment]
Just realised this is duplicate from #132, please also refer there.
