### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by SadarAzmoun** [BiomedicalMachineLearning/stLearn#163]
Dear Developers,

I'm trying to run st.pl.gene_plot_interactive(data), and I want to use Bokeh to output the interactive gene plot to html file rather than output to notebook.
So I modify the gene_plot_interactive(adata: AnnData) function in "D:\Anaconda3\lib\site-packages\stlearn\plotting\gene_plot.py" like this:
    output_file(filename="test.html")
    show(bokeh_object.app)

but I face "AssertionError" as shown below:
reading D:\spatialProject\lung_SARS-CoV-2\V10F24-110_C1\filtered_feature_bc_matrix.h5
 (0:00:00)
Traceback (most recent call last):
  File "D:/PycharmProjects/untitled/test.py", line 19, in <module>
    st.pl.gene_plot_interactive(data)
  File "D:\Anaconda3\lib\site-packages\stlearn\plotting\gene_plot.py", line 113, in gene_plot_interactive
    show(bokeh_object.app)
  File "D:\Anaconda3\lib\site-packages\bokeh\io\showing.py", line 152, in show
    assert state.notebook_type is not None
AssertionError

I would like to know how to fix the bug or other way to output dynamic html.
Thank you again for your excellent work.

**Comment by duypham2108** [comment]
Because the bokeh_object.app is an app then you cannot export the whole app directly. The only way to export html is exporting static html file for one gene at a time (you still can use the toolbar like zoom, just cannot change the parameter when generating plot).

I recommend you to use this one:
```
from stlearn.plotting.classes_bokeh import BokehGenePlot
from bokeh.plotting import output_file, save

# Change the gene name
bokeh_object.gene_select.value = "Gene_symbol"

# Export html file
output_file(filename="custom_filename.html", title="Static HTML file")
save(bokeh_object.make_fig())
```

You also can change other parameters based on this main plotting function: https://github.com/BiomedicalMachineLearning/stLearn/blob/b7270ceaae4199e2f7b7c38b8836b297be0c5376/stlearn/plotting/classes_bokeh.py#L144
