### ISSUE TITLE
Find CCI on simulated data - hyperparameters and runtime

### ISSUE THREAD

**Issue by joeyhbao** [BiomedicalMachineLearning/stLearn#178]
Dear Developers, 

I'm trying to test stLearn by running it on a simulated dataset. I followed your instruction for "[stLearn Cell-Cell Interaction Analysis](https://stlearn.readthedocs.io/en/latest/tutorials/stLearn-CCI.html)" and got to the step Predicting significant CCIs with st.tl.cci.run_cci. My issues are: 
1. In our simulated dataset, CCI are supposed to be found between most cell types, but we can only find interaction from CT1 and CT4 (see image below)
![image](https://user-images.githubusercontent.com/33188234/175321113-4ba5a1b8-5498-45b0-a4ad-c850efc9bd25.png)
2. sometimes it takes about half a day to run st.tl.cci.run_cci.

I'm wondering if there are any mistakes in my hyperparameter settings. My dataset has ~7500 cells in a 100x100 grid. There are 15 ligands, 15 receptors, and ~40 non-LR genes.

I used the following hyperparameters: 
```
st.tl.cci.run_cci(data,'cell_type', min_spots=20,spot_mixtures=False,cell_prop_cutoff=0.2,
                sig_spots=True,n_perms=1000)
```
I tried to vary min_spots between [3,7,11,15,20], but the resulting CCI did not change.

**Comment by BradBalderson** [comment]
Hi Joey!

Think the issue might be due to st.tl.cci.run. 

From #161 stLearn CCI uses non-LR genes with similar expression distributions to the LR genes to generate a background to identify spots/cells/neighbourhoods with high LR coexpression (assumes LRs have non-random spatial coexpression and non-LR random pairs have random spatial coexpression).

The 40 non-LR genes, if they don't represent the full range of expression in the LR genes, may result in no hotspots being identified for many LRs and introduce bias due to LR expression level/frequency. 

If these happen to be in regions where certain cell types are found, would result in no interactions between these cell types. 

Unfortunately might be abit of a mismatch between the simulated and real data in this case (in real data our approach works really well to reduce bias toward highly/lowly expressed LRs).

What does the plot from this look like? Think this would show strong bias of results based on high/low LR expression due to lack of background genes to correct for LR expression level:
`st.pl.lr_diagnostics(data, figsize=(10,2.5)
`
I could spend more time optimising run_cci (currently haven't implemented parallelisation). Due to time constraints might have to leave that for stLearn CCI V2! 

In the meantime, could I suggest simulating more non-LR genes prior to running st.tl.cci.run? Maybe 5000? And with similar simulation parameters used for the LR genes? Think that will improve any bias you see when you plot st.pl.lr_diagnostics(data, figsize=(10,2.5). 

Cheers
