### ISSUE TITLE
Problem with GO enrichment analysis

### ISSUE THREAD

**Issue by jk86754** [BiomedicalMachineLearning/stLearn#192]
Please see below.

![image](https://user-images.githubusercontent.com/11413558/191753558-50c7e0b7-fd09-455c-b52b-9df8517d2008.png)
Help would be appreciated.

**Comment by BradBalderson** [comment]
run_lr_go wraps R using rpy2. Requires a certain R setup. There is some detailed provided in the text above that code:

```
For the R dependencies, please see the following links for installation: [clusterProfiler](https://www.bioconductor.org/packages//2.10/bioc/html/clusterProfiler.html), [org.Hs.eg.db](https://bioconductor.org/packages/release/data/annotation/html/org.Hs.eg.db.html), [org.Mm.eg.db](https://bioconductor.org/packages/release/data/annotation/html/org.Mm.eg.db.html).

To get the path to your R installation, simply type the following into your terminal: which R
```

**Comment by jk86754** [comment]
Thanks. I have all of these packages installed. May the error be due to an
incorrect IRanges version issue?

**Comment by BradBalderson** [comment]
Could be, I can't really provide much support for getting clusterProfiler installed properly sorry (hence "Advanced Users" label for that section).  Think it's worth trying to load it in R and make sure it's installed properly their first, before trying to use the rpy2 wrapper. Will probably be very difficult to debug otherwise
