### ISSUE TITLE
runtime about cci

### ISSUE THREAD

**Issue by jinyuanchun** [BiomedicalMachineLearning/stLearn#198]
my dataset contains about 45,000 spots, and about 10,000 genes.  Cell communication analysis has not been completed since September 26.
so,Can you tell me the general running time in datasets of different sizes?

**Comment by BradBalderson** [comment]
OH wow that's alot. It's pretty dataset dependent; if the sequencing depth is good will take longer because more spots to test (since LRs expressed in more spots). 

Is the slow part run_cci or run? If it's latter than due to above & aside from binning spots/cells not much can do (maybe specify more cpus?). If it's run_cci, I can make this faster (haven't had chance to optimise run speed of this yet).

**Comment by jinyuanchun** [comment]
run_cci is the slow part.

**Comment by BradBalderson** [comment]
Got it. Alright I should have some 'free' time early next week & will take some time to speed it up. Compiling with numba & parallelising should get it atleast 100-1000X faster.

**Comment by jinyuanchun** [comment]
thank you

**Comment by BradBalderson** [comment]
Sorry about that @jinyuanchun, the run_cci function has now been parallelised and JIT compiled so is much faster now. 

Also it shows a progress bar, to give you an idea of expected run time. 

If this is still too slow (which it's possible it is, considering you have ALOT of spots), perhaps you can also consider performing a grid operation, described in the new Xenium tutorial here:

https://stlearn.readthedocs.io/en/latest/tutorials/Xenium_CCI.html

**Comment by leiLQ** [comment]
Hi @BradBalderson, I tried to re-run the run_cci step on the same gridded xenium data in the stlearn tutorial. But it can't finish in 40 hours with 50 cpus. 

Would you mind suggesting how much time and how many cpus were used for your team to successfully run this step?
