### ISSUE TITLE
same cell type in cci

### ISSUE THREAD

**Issue by jinyuanchun** [BiomedicalMachineLearning/stLearn#230]
I have a result that all involve interactions between the same cell types
![image](https://user-images.githubusercontent.com/40689145/235077335-93f131ec-adc6-4dd0-bebb-3d5c526e758b.png)

how to Perform interaction analysis after removing the same cell type

**Comment by BradBalderson** [comment]
They are the only ones significant? Can't really remove the same celltype, since it needs to be in the data to test if it interacts with others.

Could I suggest perhaps plotting it without the significance filtering? Or perhaps at multiple different p-value cutoffs? Just to help give you a sense of what are the slightly weaker interactions between other cell types that were not considered significant.

**Comment by jinyuanchun** [comment]
Thank you for your suggestion. I checked the raw results (per_lr_cci_raw_cell_type) and found that there were only interactions of the same cell type. Because previous studies have found that the interaction between reaEGC and WSN is an important molecular basis for brain injury regeneration in axolotl, attention should be paid to the interaction between different cell types.
