### ISSUE TITLE
Reading in MERFISH data gives back IndexError: positional indexers are out-of-bounds. 

### ISSUE THREAD

**Issue by Laura-Waechter** [BiomedicalMachineLearning/stLearn#235]
Hi everyone,

I am trying to read in some data (https://info.vizgen.com/mouse-liver-access) with the stlearn.readMERFISH() function (stlearn version 0.4.12 and python 3.8) and am getting the IndexError: positional indexers are out-of bounds. The spatial file and the counts file have the same number of rows though. How can I solve this or what might be the problem?

Thanks in advance!

**Comment by duypham2108** [comment]
It might outdated function. I will check it soon
Can you try this tutorial to read MERFISH data?
https://stlearn.readthedocs.io/en/latest/tutorials/Read_any_data.html

**Comment by duypham2108** [comment]
Sorry for the late reply. 

> I was wondering whether I can apply this workflow to my data and if I could read in preprocessed data from squidpy to proceed with this analysis?

> When I use the function st.convert_scanpy, I get the KeyError 'scalefactors', even if I didn't scale and logarithmize the data.

I think you would need to repeat all steps despite log1p (recommend). For the h5ad option, there will be some issues due to we used different variable names in the data object. You may need to export their anndata to csv file and read it again.

> I was also wondering about the label transfer results mentioned there. Can I use the assignment of cell types instead?

Yes, you can use any cell type information but it's a bit tricky. We provide a function `grid` here to treat a group of cells as a spot (just like converting MERFISH or any single cell data to spot-based data. The label here will automatically save as a deconvolution result). Check here: https://stlearn.readthedocs.io/en/latest/tutorials/Xenium_CCI.html#Gridding). It's also related to performance issues. Hope this helps

**Comment by Laura-Waechter** [comment]
Thanks, I will try that.
