### ISSUE TITLE
Trajectory Zoom

### ISSUE THREAD

**Issue by meaksu** [BiomedicalMachineLearning/stLearn#282]
Hi,
Thanks for developing this package. I had a few questions about the Trajectory analysis for my Xenium sample.

1. It seems like generating a zoomed image flips the tissue across the y-axis, is there a way to fix this?

<img width="719" alt="Capture1" src="https://github.com/BiomedicalMachineLearning/stLearn/assets/71838948/e963951d-e731-48f4-8de2-5f586bd20099">
<img width="570" alt="Capture2" src="https://github.com/BiomedicalMachineLearning/stLearn/assets/71838948/a6b7a3c9-c804-4b2f-80da-6fc5a8c8ae15">

2. Also, is there a way to speed up the st.spatial.trajectory.pseudotime function? For example if I'm only interested in a particular region of the tissue, would it be valid to subset based on those zoomed coordinates before running the trajectory, and if so what would be the best way to do this?

**Comment by duypham2108** [comment]
Sorry I just back from a long holiday. It might be a problem with the x-y order. I will fix it soon.
Currently, we use DBSCAN in one step for spatial clustering. If you see many sub-clusters in `.obs['sub_cluster_labels']` then the parameter `eps` may be too small which causes the slow issue. Increasing it can be a solution. If not, we may update an HDBSCAN option instead of DBSCAN

**Comment by duypham2108** [comment]
I fixed the zoom issue in the master branch version.
```
pip uninstall stlearn --yes
git clone https://github.com/BiomedicalMachineLearning/stLearn.git
cd stLearn
python setup.py install
```
