### ISSUE TITLE
Setting root for Pseudotime analysis

### ISSUE THREAD

**Issue by kerimsecener** [BiomedicalMachineLearning/stLearn#86]
Hey,

Thanks for the amazing tool !

Could you be more specific regarding how you set the root for the trajectory analysis:

`3733 is the index of the spot that we chose as root. It in the DCIS cluster (6). We recommend the root spot should be in the end/begin of a cluster in UMAP space. You can find min/max point of a cluster in UMAP as root.`

So, here you set the spot # 3733 in the DCIS cluster as root. How do you get this index? The rest of the statement is quite unclear as to if I should get the index from UMAP embedding of the spots/cells or from the spot-overlaid tissue image? And what is the idea behind min/max selection?

Could you share an example snippet for this step as to how to select a spot index as a root node?

Happy to share more information.

Thanks,
Kerim

**Comment by duypham2108** [comment]
Thank you for using our toolkit.

In this step, we are using only UMAP space to specify the root. Suppose we have x-axis (0) and y-axis (1) of the UMAP space. The spot on the edge (max/min of x/y-axis) is the best to reflect the original state of a cluster rather than a random spot in a cluster (very sensitive in spatial transcriptomics when we map to spatial data). Notice that you also need to consider the position of the cluster to choose max/min of x/y-axis. For example, cluster 6 is located in the bottom-right then the root should be the bottom-right edge of the cluster -> We choose min of the y-axis spot.

Here is an example of how I select root:

```python
import numpy as np
# Get all index of cluster 6
list_idx_cluster_6 = np.flatnonzero(data.obs["louvain"]  == str(6))
# Get min/max index of the x-axis (0) or y-axis (1) dimension of X_umap 
idx_min = np.argmin(data.obsm["X_umap"][data.obs["louvain"]  == str(6)][:,1], axis=0)
# Get the root index. Here is 3733
data.uns["iroot"] = list_idx_cluster_6[idx_min]

```

![image](https://i.imgur.com/3fUYRSq.png)

**Comment by kerimsecener** [comment]
Thanks a lot for the fast reply ! It is all clear for me now.

**Comment by LipingChen0607** [comment]
Could you tell me how to plot the two UMAP space images above? Thanks a lot!

**Comment by duypham2108** [comment]
For the first plot, you can use scanpy.pl.umap or matplotlib with adata.obsm["X_umap"].
Currently, we changed the way to set the root as automatic function `st.spatial.trajectory.set_root`. The root index stores in `adata.uns["iroot"]`. You can change the color of that to make the second plot
